### ISSUE TITLE
Using `tlm_sterodynamics_project_cmip.py` for testing

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#330]
I wonder if there is a simple switch implanted to use `tlm_sterodynamics_project_cmip.py` instead of the `tlm_sterodynamics_project.py` or why is this script still included in the module scripts? Can this method be used instead of the thermal expansion from the climate emulator output? Is there a way to choose this method in the config file? Even though this would make the sterodynamic output inconsistent with the other sea level component estimate, it might be a useful tool to test how sensitive the variances decomposition is to the representation of the thermal expansion.
https://github.com/radical-collaboration/facts/blob/3ff08f91a8d8180b7058f8bcad884f0dc46dce53/modules/tlm/sterodynamics/tlm_sterodynamics_project_cmip.py#L27

**Comment by bobkopp** [comment]
I can’t vouch for the code. You would have to create a new pipeline.cmip.yml file and specify that it be used instead of pipeline.yml in your experiment file.
________________________________
From: Jan-Erik Tesdal ***@***.***>
Sent: Tuesday, April 30, 2024 5:14:01 PM
To: radical-collaboration/facts ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [radical-collaboration/facts] Using `tlm_sterodynamics_project_cmip.py` for testing (Issue #330)


I wonder if there is a simple switch implanted to use tlm_sterodynamics_project_cmip.py instead of the tlm_sterodynamics_project.py or why is this script still included in the module scripts? Can this method be used instead of the thermal expansion from the climate emulator output? Is there a way to choose this method in the config file? Even though this would make the sterodynamic output inconsistent with the other sea level component estimate, it might be a useful tool to test how sensitive the variances decomposition is to the representation of the thermal expansion.
https://github.com/radical-collaboration/facts/blob/3ff08f91a8d8180b7058f8bcad884f0dc46dce53/modules/tlm/sterodynamics/tlm_sterodynamics_project_cmip.py#L27
