### ISSUE TITLE
Question: What is the reason for the difference in spread of projections from the tlm/sterodynamics module in FACTS 1.1 compared to FACTS 1.0?

### ISSUE THREAD

**Issue by jetesdal** [radical-collaboration/facts#336]
Figure 12 in the [FACTS 1.1.1 technical note](https://fact-sealevel.readthedocs.io/en/latest/_downloads/1f34d299c5931ffc0fe80ede1ac2b9c5/FACTS-1.1.1.pdf) shows projections of 2100 GMSL from the `tlm/sterodynamics` module as a function of GSAT in FACTS 1.1 and FACTS 1.0. The spread in GMSL from FACTS-1.1. is more constrained than in FACTS-1.0. I could not find a description of this figure (besides the figure caption) in the technical note and I am wondering what the reason is for the different spread between the two FACTS versions.

**Comment by bobkopp** [comment]
FACTS v1.1 preserves a 1:1 mapping between global-mean surface air temperature (GSAT) samples and sea-level samples. In FACTS v1.0, some modules broke this mapping by resampling temperature and ocean-heat content in a random fashion that originally made sense but no longer does. This was not an issue in the application to IPCC AR6, since AR6 was not attempting to preserve traceability of sea level projections to individual temperature samples, but it was a critical issue for some applications (e.g., projection of sea level under probabilistic emissions scenarios).
